### ISSUE TITLE
How to run it on WSL?

### ISSUE THREAD

**Issue by francescofugazzi** [NVIDIAGameWorks/kaolin-wisp#8]
I prepared and compiled everything but it triggers errors when trying to load it under wsl.
It starts loading the dataset (i'm trying with the default fox) but then it stops

**Comment by tovacinni** [comment]
Hi Francesco, 

Thanks for your interest in kaolin-wisp! 

We haven't tested on WSL but would love to try to help out. Can you send us more detailed error messages if there are any?

**Comment by 3a1b2c3** [comment]
I made some way into running it on windows. Its there headless but i see no gui backend called app.use("glfw_imgui"), did you use a branch or anything special?
https://github.com/glumpy/glumpy/pull/177/files

**Comment by 3a1b2c3** [comment]
Ah the fox doesnt have the expected training/test split folder structure, use lego data set, that worked for me. Maybe worth updating docs

**Comment by 3a1b2c3** [comment]
![image](https://user-images.githubusercontent.com/74843139/184471009-1bdcef28-df2f-4db3-9c9d-6d2167f0771c.png)
seems fixed now

**Comment by Caenorst** [comment]
Hi @francescofugazzi , are you using `--dataset-num-workers` ? If yes there can be some issues with multiprocessing on container if you don't set IPC to be shared from host.

**Comment by francescofugazzi** [comment]
hi @Caenorst 
I left the WSL path and I directly set and Ubuntu environment for trying this
It still doesn't work to me :(
I tried with some instant-ngp datasets but it always get killed
```
2022-08-23 16:23:03,118|    INFO| Position Embed Dim: 63
2022-08-23 16:23:03,119|    INFO| View Embed Dim: 27
loading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 59/59 [00:02<00:00, 21.09it/s]
2022-08-23 16:23:06,144|    INFO| WARNING: The dataset expects distortion correction, but the current implementation does not handle this.
/home/franzipol/anaconda3/envs/kaolin/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484683044/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Killed

```

**Comment by Caenorst** [comment]
@francescofugazzi can I have a little bit more info about your system?
Ubuntu version, Pytorch version, python version, GPU, RAM quantity, CUDA version, drivers version?

**Comment by francescofugazzi** [comment]
Ububtu 20.04
Pytorch 1.12
Python 3.8
RTX 3070 mobile with 8GB Vram
CUDA 11.6
I don't have the driver version available as right now i'm onto another system but i think they were the latest available
Everything was a fresh install

**Comment by Caenorst** [comment]
@francescofugazzi can you open a new issue? it will help other people to search whenever they have similar issue (I suspect an OOM)

**Comment by orperel** [comment]
WSL support have been fixed with #105
